In [1]:
from DG import *

In [2]:
df,gr,we,cf = genSynthData()

In [3]:
df

,f0,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,y
0,-1.875001,-1.803841,-0.207979,-0.612318,0.249337,-0.621231,-0.661710,2.196547,-1.395003,-0.139938,0.121892,-41.532363
1,-1.306635,-0.313156,1.434609,-2.024274,1.429174,0.542080,-0.813951,1.957361,0.608410,0.904190,-0.599910,-5.805320
2,-0.191622,-0.325814,-0.678752,-0.096515,0.844624,0.585228,1.053465,-2.715644,-0.735906,-1.360839,0.537873,46.813720
3,-1.238807,-1.644363,-2.131455,0.755104,0.054945,-0.190784,0.519929,-0.237019,0.950004,-0.439747,0.247936,-36.448080
4,-2.856516,-2.512372,-1.125856,0.132390,-1.036243,0.768130,0.588408,0.017858,0.710135,0.881649,0.469530,-51.602205
...,...,...,...,...,...,...,...,...,...,...,...,...
395,1.167423,0.914286,0.029958,0.181050,-0.479761,-0.323844,1.008536,1.080291,0.725531,0.183430,1.073573,-1.589216
396,-0.671465,-0.798811,-1.194040,0.781180,-1.694706,-0.731138,-1.197431,0.244767,0.990249,-0.419275,0.529466,-37.306507
397,0.433722,0.672755,-0.200679,0.440735,-0.337493,-0.773611,-1.422957,-0.513479,-1.247800,-1.356507,0.159496,3.855586
398,-0.403663,0.569963,0.341821,-0.329418,0.499903,-1.133354,-0.557170,-1.078078,1.440180,1.210393,-0.431745,-6.837055
399,0.434043,-1.496382,-2.148347,0.172230,1.932535,-0.627944,-1.310420,-0.793278,-0.774224,-0.281452,0.284858,-20.066736

In [4]:
gr

[5]

In [5]:
we

[[0.818285283966157,
  0.8540554519136347,
  -0.6591931174956939,
  -0.5072915120959917]]

In [6]:
#colouring function 
def color_thresh(val,thres=0.5):
    if abs(val)>=thres:
        if val<0:
            return 'background-color: red'
        else:
            return 'background-color: green'
    else:
        return ''

In [13]:
display(df.iloc[:,:-1].corr().style.applymap(color_thresh))